[package]
name = "conmon-rs"
version = "0.1.0"
edition = "2021"

[[bin]] # Bin to run the ConmonServer gRPC server
name = "conmon-server"
path = "src/server.rs"

[[bin]]
name = "conmon-client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.45"
async-stream = "0.3.2"
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"] }
futures = "0.3.17"
getset = "0.1.1"
log = { version = "0.4.14", features = ["serde", "std"] }
prost = "0.9.0"
serde = { version = "1.0.130", features = ["derive"] }
simple_logger = "1.13.0"
tokio = { version = "1.13.0", features = ["fs", "macros", "process", "rt", "signal", "time"] }
tonic = "0.6.1"
tower = "0.4.10"
gettext-rs = "0.7.0"

[build-dependencies]
tonic-build = "0.6.0"

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1

[dev-dependencies]
nix = "0.23.0"
