[package]
name = "conmon"
version = "0.1.0-dev"
edition = "2018"

[[bin]]
name = "conmonrs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.58"
capnp = "0.14.8"
capnp-rpc = "0.14.1"
conmon-common = { path = "../common" }
clap = { version = "3.1.17", features = ["cargo", "derive", "env", "wrap_help"] }
futures = "0.3.21"
getset = "0.1.2"
serde = { version = "1.0.140", features = ["derive"] }
tokio = { version = "1.20.0", features = ["fs", "io-std", "io-util", "macros", "net", "process", "rt", "rt-multi-thread", "signal", "time"] }
tokio-util = { version = "0.7.3", features = ["compat"] }
nix = "0.24.2"
libc = "0.2.126"
memchr = "2.5.0"
tempfile = "3.3.0"
sendfd = { version = "0.4.3", features = ["tokio"] }
prctl = "1.0.0"
strum = { version = "0.24.1", features = ["derive"] }
shadow-rs = "0.15.0"
multimap = "0.8.3"
tracing = "0.1.35"
tracing-journald = "0.3.0"
tracing-subscriber = "0.3.14"
uuid = { version = "1.1.2", features = ["v4", "fast-rng", "macro-diagnostics"] }
regex = "1.6.0"
notify = "5.0.0-pre.15"
tokio-eventfd = "0.2.0"
lazy_static = "1.4.0"
tz-rs = "0.6.11"

[build-dependencies]
shadow-rs = "0.15.0"

[dev-dependencies]
mockall = "0.11.1"
time = { version = "0.3.11", features = ["parsing"] }
