[package]
name = "conmon"
version = "0.1.0-dev"
edition = "2018"

[[bin]]
name = "conmonrs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.57"
capnp = "0.14.6"
capnp-rpc = "0.14.1"
chrono = "0.4.19"
conmon-common = { path = "../common" }
clap = { version = "3.1.9", features = ["cargo", "derive", "env", "wrap_help"] }
futures = "0.3.21"
getset = "0.1.2"
log = { version = "0.4.16", features = ["serde", "std"] }
serde = { version = "1.0.136", features = ["derive"] }
simple_logger = "2.1.0"
tokio = { version = "1.17.0", features = ["fs", "io-std", "io-util", "macros", "net", "process", "rt", "rt-multi-thread", "signal", "time"] }
tokio-util = { version = "0.7.1", features = ["compat"] }
nix = "0.24.0"
libc = "0.2.124"
memchr = "2.4.1"
tempfile = "3.3.0"
sendfd = { version = "0.4.1", features = ["tokio"] }
prctl = "1.0.0"
strum = { version = "0.24.0", features = ["derive"] }
systemd-journal-logger = "0.5.0"
shadow-rs = "0.11.0"
multimap = "0.8.3"

[build-dependencies]
shadow-rs = "0.11.0"

[dev-dependencies]
mockall = "0.11.0"
