[package]
name = "conmon-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "conmon-server"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.51"
capnp = "0.14.3"
capnp-rpc = "0.14.1"
conmon-common = { path = "../common" }
clap = { git = "https://github.com/clap-rs/clap", features = ["wrap_help"] }
futures = "0.3.18"
getset = "0.1.2"
log = { version = "0.4.14", features = ["serde", "std"] }
serde = { version = "1.0.130", features = ["derive"] }
simple_logger = "1.15.0"
tokio = { version = "1.14.0", features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
tokio-util = { version = "0.6.9", features = ["compat"] }
nix = "0.23.0"
libc = "0.2.108"

[dev-dependencies]
mockall = "0.10.2"
tempfile = "3.2.0"
