[package]
name = "conmonrs-cli"
version = "0.1.0"
edition = "2018"

[dependencies]
async-io = "1.6.0"
async-net = "1.6.1"
capnp = "0.14.6"
capnp-rpc = "0.14.1"
conmon-common = { path = "../common" }
futures = "0.3.21"
log = { version = "0.4.16", features = ["serde", "std"] }
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.18.0", features = ["fs", "macros", "net", "process", "rt", "signal", "time"] }
